// https://eslint.org/docs/latest/user-guide/configuring/configuration-files-new
// https://eslint.org/blog/2022/08/new-config-system-part-1/
// https://eslint.org/blog/2022/08/new-config-system-part-2/

import typescriptEslintPlugin from "@typescript-eslint/eslint-plugin";
import * as typescriptEslintParser from "@typescript-eslint/parser";
import * as espreeParser from "espree";
import * as AstroEslintParser from "astro-eslint-parser";
import astroEslintPlugin from "eslint-plugin-astro";
import globals from "globals";

const eslintConfig = [
	{
		files: ["**/*.mjs", "**/*.js", "**/*.ts", "**/*.astro"],
		languageOptions: {
			sourceType: "module",
		},
	},
	{
		files: ["**/*.cjs"],
		languageOptions: {
			sourceType: "commonjs",
		},
	},
	{
		files: ["**/*.mjs", "**/*.js", "**/*.ts", "**/*.cjs", "**/*.astro"],
		languageOptions: {
			globals: {
				...globals.node,
			},
		},
	},
	{
		languageOptions: {
			ecmaVersion: 13,
			globals: {
				...globals.es2021,
			},
		},
		rules: {
			"constructor-super": "error",
			"for-direction": "error",
			"getter-return": "error",
			"no-async-promise-executor": "error",
			"no-case-declarations": "error",
			"no-class-assign": "error",
			"no-compare-neg-zero": "error",
			"no-cond-assign": "error",
			"no-const-assign": "error",
			"no-constant-condition": "error",
			"no-control-regex": "error",
			"no-debugger": "error",
			"no-delete-var": "error",
			"no-dupe-args": "error",
			"no-dupe-class-members": "error",
			"no-dupe-else-if": "error",
			"no-dupe-keys": "error",
			"no-duplicate-case": "error",
			"no-empty": "error",
			"no-empty-character-class": "error",
			"no-empty-pattern": "error",
			"no-ex-assign": "error",
			"no-extra-boolean-cast": "error",
			"no-fallthrough": "error",
			"no-func-assign": "error",
			"no-global-assign": "error",
			"no-import-assign": "error",
			"no-inner-declarations": "error",
			"no-invalid-regexp": "error",
			"no-irregular-whitespace": "error",
			"no-loss-of-precision": "error",
			"no-misleading-character-class": "error",
			"no-new-symbol": "error",
			"no-nonoctal-decimal-escape": "error",
			"no-obj-calls": "error",
			"no-octal": "error",
			"no-prototype-builtins": "error",
			"no-redeclare": "error",
			"no-regex-spaces": "error",
			"no-self-assign": "error",
			"no-setter-return": "error",
			"no-shadow-restricted-names": "error",
			"no-sparse-arrays": "error",
			"no-this-before-super": "error",
			"no-undef": "error",
			"no-unreachable": "error",
			"no-unsafe-finally": "error",
			"no-unsafe-negation": "error",
			"no-unsafe-optional-chaining": "error",
			"no-unused-labels": "warn",
			"no-unused-vars": ["warn", {ignoreRestSiblings: true}],
			"no-useless-backreference": "error",
			"no-useless-catch": "error",
			"no-useless-escape": "error",
			"no-with": "error",
			"require-yield": "error",
			"use-isnan": "error",
			"valid-typeof": "error",
		},
	},
	{
		files: ["**/*.ts", "**/*.astro"],
		rules: {
			"@typescript-eslint/adjacent-overload-signatures": "error",
			"@typescript-eslint/ban-ts-comment": "error",
			"@typescript-eslint/ban-types": "error",
			"no-array-constructor": "off",
			"@typescript-eslint/no-array-constructor": "error",
			"@typescript-eslint/no-explicit-any": "warn",
			"@typescript-eslint/no-extra-non-null-assertion": "error",
			"@typescript-eslint/no-inferrable-types": "error",
			"no-loss-of-precision": "off",
			"@typescript-eslint/no-loss-of-precision": "error",
			"@typescript-eslint/no-misused-new": "error",
			"@typescript-eslint/no-namespace": "error",
			"@typescript-eslint/no-non-null-asserted-optional-chain": "error",
			"@typescript-eslint/no-non-null-assertion": "warn",
			"@typescript-eslint/no-this-alias": "error",
			"@typescript-eslint/no-unnecessary-type-constraint": "error",
			"no-unused-vars": "off",
			"@typescript-eslint/no-unused-vars": ["warn", {ignoreRestSiblings: true}],
			"@typescript-eslint/no-var-requires": "error",
			"@typescript-eslint/prefer-as-const": "error",
			"@typescript-eslint/prefer-namespace-keyword": "error",
			"@typescript-eslint/triple-slash-reference": "error",
		},
		plugins: {
			"@typescript-eslint": typescriptEslintPlugin,
		},
	},
	{
		files: ["**/*.ts"],
		languageOptions: {
			parser: typescriptEslintParser,
			parserOptions: {
				project: "./tsconfig.json",
				tsconfigRootDir: ".",
				extraFileExtensions: [".astro"],
			},
		},
	},
	{
		files: ["**/*.js", "**/*.cjs", "**/*.mjs"],
		languageOptions: {
			parser: espreeParser,
		},
	},
	{
		files: ["**/*.astro"],
		languageOptions: {
			parser: AstroEslintParser,
			parserOptions: {
				parser: typescriptEslintParser,
				extraFileExtensions: [".astro"],
			},
		},
		plugins: {
			"astro": astroEslintPlugin,
		},
		rules: {
			"astro/no-conflict-set-directives": "error",
			"astro/no-deprecated-astro-canonicalurl": "error",
			"astro/no-deprecated-astro-fetchcontent": "error",
			"astro/no-deprecated-astro-resolve": "error",
			"astro/no-unused-define-vars-in-style": "error",
			"astro/valid-compile": "error",
			"astro/no-set-html-directive": "error",
			"astro/no-set-text-directive": "error",
			"astro/no-unused-css-selector": "error",
			"astro/prefer-class-list-directive": "error",
			"astro/prefer-object-class-list": "error",
			"astro/prefer-split-class-list": "error",
			"astro/jsx-a11y/alt-text": "error",
			"astro/jsx-a11y/anchor-ambiguous-text": "error",
			"astro/jsx-a11y/anchor-has-content": "error",
			"astro/jsx-a11y/anchor-is-valid": "error",
			"astro/jsx-a11y/aria-activedescendant-has-tabindex": "error",
			"astro/jsx-a11y/aria-props": "error",
			"astro/jsx-a11y/aria-proptypes": "error",
			"astro/jsx-a11y/aria-role": "error",
			"astro/jsx-a11y/aria-unsupported-elements": "error",
			"astro/jsx-a11y/autocomplete-valid": "error",
			"astro/jsx-a11y/click-events-have-key-events": "error",
			"astro/jsx-a11y/control-has-associated-label": "error",
			"astro/jsx-a11y/heading-has-content": "error",
			"astro/jsx-a11y/html-has-lang": "error",
			"astro/jsx-a11y/iframe-has-title": "error",
			"astro/jsx-a11y/img-redundant-alt": "error",
			"astro/jsx-a11y/interactive-supports-focus": "error",
			"astro/jsx-a11y/label-has-associated-control": "error",
			"astro/jsx-a11y/lang": "error",
			"astro/jsx-a11y/media-has-caption": "error",
			"astro/jsx-a11y/mouse-events-have-key-events": "error",
			"astro/jsx-a11y/no-access-key": "error",
			"astro/jsx-a11y/no-aria-hidden-on-focusable": "error",
			"astro/jsx-a11y/no-autofocus": "error",
			"astro/jsx-a11y/no-distracting-elements": "error",
			"astro/jsx-a11y/no-interactive-element-to-noninteractive-role": "error",
			"astro/jsx-a11y/no-noninteractive-element-interactions": "error",
			"astro/jsx-a11y/no-noninteractive-element-to-interactive-role": "error",
			"astro/jsx-a11y/no-noninteractive-tabindex": "error",
			"astro/jsx-a11y/no-redundant-roles": "error",
			"astro/jsx-a11y/no-static-element-interactions": "error",
			"astro/jsx-a11y/prefer-tag-over-role": "error",
			"astro/jsx-a11y/role-has-required-aria-props": "error",
			"astro/jsx-a11y/role-supports-aria-props": "error",
			"astro/jsx-a11y/scope": "error",
			"astro/jsx-a11y/tabindex-no-positive": "error",
		},
	},
	{
		ignores: [
			"**/node_modules/**",
			"build/**",
			".svelte-kit/**",
			"pnpm-lock.yaml",
			"package-lock.json",
			"yarn.lock",
			"dist/**",
			"coverage/**",
			"**/.vscode/**",
			"coverage_report/**",
			"**/.git/**",
		],
	},
];

export default eslintConfig;
