env:
  NODEJS_VERSION: "22.3.0"
jobs:
  lint_commit_message:
    name: "Lint the commit message"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@v4"
      - name: "Setup Node.js"
        uses: "actions/setup-node@v4"
        with:
          cache: "npm"
          node-version: "${{env.NODEJS_VERSION}}"
      - name: "Install dependencies"
        run: |
          npm ci
      - name: "Lint the commit message with commitlint"
        run: |
          npx commitlint --last
name: "Ensure the Conventional Commits convention on push"
on:
  push:
